apiVersion: apps/v1
kind: Deployment
metadata:
  name: zull
  labels:
    app: zull
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zull
  template:
    metadata:
      labels:
        app: zull
    spec:
      containers:
      - name: zull
        image: janmenjaya/zull
        ports:
        - containerPort: 30002  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0    

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: zull
  name: zull
  namespace: default
spec:
  clusterIP: 10.110.193.61
  clusterIPs:
  - 10.110.193.61
  internalTrafficPolicy: Cluster
  ports:
  - port: 30002
    protocol: TCP
    targetPort: 30002
  selector:
    app: zull
  sessionAffinity: None
  type: ClusterIP
