apiVersion: apps/v1
kind: Deployment
metadata:
  name: zull
  labels:
    app: zull
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zull
  template:
    metadata:
      labels:
        app: zull
    spec:
      containers:
      - name: zull
        image: janmenjaya/zull
        ports:
        - containerPort: 30002
